### ISSUE TITLE
RuntimeWarning: coroutine 'index.<locals>.do_search' was never awaited

### ISSUE THREAD

**Issue by TaoshanS** [zdimension/plexdlweb#1]
Hi, I just setup the script with all of the neccesary Plex data. I got it working until I try to search for something, then I get:

`/home/USERNAME/.local/lib/python3.10/site-packages/nicegui/elements/timer.py:66: RuntimeWarning: coroutine 'index.<locals>.do_search' was never awaited
  await self._invoke_callback()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
`
I tried looking for the issue but can't find it.

I would also like to propose the idea of a docker image but that probably goes to another issue.

**Comment by zdimension** [comment]
I was using Python 3.9 on my local setup, I'm gonna try to replicate it with 3.10; I'll keep this thread updated.

**edit:** yep, calling an async function from a NiceGUI timer. It was working before, but now it seems it doesn't handle coroutines anymore. Investigating.

Docker would be a good idea, you can create a second issue if you want.

**Comment by zdimension** [comment]
@TaoshanS should be fixed with latest commit (7e687247f55c690ccc561c79befe42c4696001e9), can you check?

**Comment by TaoshanS** [comment]
Now I am allowed to search for content and download. Everything seems to work as intended. However there are two more things: images don't appear in content.
![imagen](https://github.com/zdimension/plexdlweb/assets/38806810/878b5939-e7b4-4628-a3a3-ca4ac6cd428d)

And the console shows this upon starting:
`AsyncConnectionPool.__init__() got an unexpected keyword argument 'socket_options'
Traceback (most recent call last):
  File "/home/USERNAME/.local/lib/python3.10/site-packages/nicegui/background_tasks.py", line 52, in _handle_task_result
    task.result()
  File "/home/USERNAME/.local/lib/python3.10/site-packages/nicegui/client.py", line 261, in result_with_client
    await result
  File "/home/USERNAME/plexdlweb/master/master/plexdlweb-master/plex.py", line 13, in startup
    app.state.httpx_client = httpx.AsyncClient()
  File "/home/USERNAME/.local/lib/python3.10/site-packages/httpx/_client.py", line 1397, in __init__
    self._transport = self._init_transport(
  File "/home/USERNAME/.local/lib/python3.10/site-packages/httpx/_client.py", line 1445, in _init_transport
    return AsyncHTTPTransport(
  File "/home/USERNAME/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 275, in __init__
    self._pool = httpcore.AsyncConnectionPool(
TypeError: AsyncConnectionPool.__init__() got an unexpected keyword argument 'socket_options'
`

Then everytime I search for something this shows up:

`'State' object has no attribute 'httpx_client'
Traceback (most recent call last):
  File "/home/USERNAME/.local/lib/python3.10/site-packages/anyio/streams/memory.py", line 98, in receive
    return self.receive_nowait()
  File "/home/USERNAME/.local/lib/python3.10/site-packages/anyio/streams/memory.py", line 93, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/USERNAME/.local/lib/python3.10/site-packages/starlette/middleware/base.py", line 78, in call_next
    message = await recv_stream.receive()
  File "/home/USERNAME/.local/lib/python3.10/site-packages/anyio/streams/memory.py", line 118, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/USERNAME/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/USERNAME/.local/lib/python3.10/site-packages/starlette/middleware/sessions.py", line 86, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/home/USERNAME/.local/lib/python3.10/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/home/USERNAME/.local/lib/python3.10/site-packages/nicegui/storage.py", line 72, in dispatch
    response = await call_next(request)
  File "/home/USERNAME/.local/lib/python3.10/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/home/USERNAME/.local/lib/python3.10/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/USERNAME/.local/lib/python3.10/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/home/USERNAME/plexdlweb/master/master/plexdlweb-master/__main__.py", line 33, in check_auth
    return await call_next(request)
  File "/home/USERNAME/.local/lib/python3.10/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/home/USERNAME/.local/lib/python3.10/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/USERNAME/.local/lib/python3.10/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/home/USERNAME/.local/lib/python3.10/site-packages/nicegui/middlewares.py", line 10, in dispatch
    response = await call_next(request)
  File "/home/USERNAME/.local/lib/python3.10/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/home/USERNAME/.local/lib/python3.10/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/USERNAME/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/USERNAME/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/USERNAME/.local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/USERNAME/.local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/USERNAME/.local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/USERNAME/.local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/USERNAME/.local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/USERNAME/.local/lib/python3.10/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/home/USERNAME/.local/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/USERNAME/plexdlweb/master/master/plexdlweb-master/plex.py", line 27, in streaming
    client = app.state.httpx_client
  File "/home/USERNAME/.local/lib/python3.10/site-packages/starlette/datastructures.py", line 705, in __getattr__
    raise AttributeError(message.format(self.__class__.__name__, key))
AttributeError: 'State' object has no attribute 'httpx_client'
ERROR:    Exception in ASGI application`

It repeats over and over.

Lastly, I noticed that partial searchs only work with the original title (I don't know if this is intended). For example using the example from the search bar, when I search _Back_ I always get Back to the Future movies. Doesn't work the same way when I search in spanish: Regreso. It may be due to the number of elements that the search shows.

**Comment by zdimension** [comment]
It seems there's a conflict with an existing `httpcore` installation, can you try `pip install httpcore==1.0`?

**Comment by TaoshanS** [comment]
Everything is working as intended. All problems solved. Thanks for your work.
