### ISSUE TITLE
server error 500 when trying to download

### ISSUE THREAD

**Issue by siddpen** [zdimension/plexdlweb#5]
![image](https://github.com/zdimension/plexdlweb/assets/4462614/9b8b1b37-86ef-42b6-8226-6d7fd8751f40)

When trying to download, I'm receiving a server error 500. log details below

```
12/22/2023
10:03:49 PM
[Errno 2] No such file or directory: '/movies/Its a Wonderful Life (1946)/Its a Wonderful Life (1946).mkv'
12/22/2023
10:03:49 PM
Traceback (most recent call last):
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/anyio/streams/memory.py", line 98, in receive
12/22/2023
10:03:49 PM
    return self.receive_nowait()
12/22/2023
10:03:49 PM
           ^^^^^^^^^^^^^^^^^^^^^
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/anyio/streams/memory.py", line 93, in receive_nowait
12/22/2023
10:03:49 PM
    raise WouldBlock
12/22/2023
10:03:49 PM
anyio.WouldBlock
12/22/2023
10:03:49 PM
12/22/2023
10:03:49 PM
During handling of the above exception, another exception occurred:
12/22/2023
10:03:49 PM
12/22/2023
10:03:49 PM
Traceback (most recent call last):
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 78, in call_next
12/22/2023
10:03:49 PM
    message = await recv_stream.receive()
12/22/2023
10:03:49 PM
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/anyio/streams/memory.py", line 118, in receive
12/22/2023
10:03:49 PM
    raise EndOfStream
12/22/2023
10:03:49 PM
anyio.EndOfStream
12/22/2023
10:03:49 PM
12/22/2023
10:03:49 PM
During handling of the above exception, another exception occurred:
12/22/2023
10:03:49 PM
12/22/2023
10:03:49 PM
Traceback (most recent call last):
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
12/22/2023
10:03:49 PM
    await self.app(scope, receive, _send)
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/sessions.py", line 86, in __call__
12/22/2023
10:03:49 PM
    await self.app(scope, receive, send_wrapper)
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 108, in __call__
12/22/2023
10:03:49 PM
    response = await self.dispatch_func(request, call_next)
12/22/2023
10:03:49 PM
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/nicegui/storage.py", line 77, in dispatch
12/22/2023
10:03:49 PM
    response = await call_next(request)
12/22/2023
10:03:49 PM
               ^^^^^^^^^^^^^^^^^^^^^^^^
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
12/22/2023
10:03:49 PM
    raise app_exc
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
12/22/2023
10:03:49 PM
    await self.app(scope, receive_or_disconnect, send_no_error)
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 108, in __call__
12/22/2023
10:03:49 PM
    response = await self.dispatch_func(request, call_next)
12/22/2023
10:03:49 PM
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
12/22/2023
10:03:49 PM
  File "/plexwebdl-app/__main__.py", line 33, in check_auth
12/22/2023
10:03:49 PM
    return await call_next(request)
12/22/2023
10:03:49 PM
           ^^^^^^^^^^^^^^^^^^^^^^^^
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
12/22/2023
10:03:49 PM
    raise app_exc
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
12/22/2023
10:03:49 PM
    await self.app(scope, receive_or_disconnect, send_no_error)
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 108, in __call__
12/22/2023
10:03:49 PM
    response = await self.dispatch_func(request, call_next)
12/22/2023
10:03:49 PM
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/nicegui/middlewares.py", line 10, in dispatch
12/22/2023
10:03:49 PM
    response = await call_next(request)
12/22/2023
10:03:49 PM
               ^^^^^^^^^^^^^^^^^^^^^^^^
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
12/22/2023
10:03:49 PM
    raise app_exc
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
12/22/2023
10:03:49 PM
    await self.app(scope, receive_or_disconnect, send_no_error)
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
12/22/2023
10:03:49 PM
    raise exc
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
12/22/2023
10:03:49 PM
    await self.app(scope, receive, sender)
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
12/22/2023
10:03:49 PM
    raise e
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
12/22/2023
10:03:49 PM
    await self.app(scope, receive, send)
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
12/22/2023
10:03:49 PM
    await route.handle(scope, receive, send)
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
12/22/2023
10:03:49 PM
    await self.app(scope, receive, send)
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
12/22/2023
10:03:49 PM
    response = await func(request)
12/22/2023
10:03:49 PM
               ^^^^^^^^^^^^^^^^^^^
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 274, in app
12/22/2023
10:03:49 PM
    raw_response = await run_endpoint_function(
12/22/2023
10:03:49 PM
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
12/22/2023
10:03:49 PM
    return await dependant.call(**values)
12/22/2023
10:03:49 PM
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
12/22/2023
10:03:49 PM
  File "/plexwebdl-app/__main__.py", line 80, in download
12/22/2023
10:03:49 PM
    return FileResponse(part.file, filename=filename, stat_result=os.stat(part.file))
12/22/2023
10:03:49 PM
                                                                  ^^^^^^^^^^^^^^^^^^
12/22/2023
10:03:49 PM
FileNotFoundError: [Errno 2] No such file or directory: '/movies/Its a Wonderful Life (1946)/Its a Wonderful Life (1946).mkv'
12/22/2023
10:03:49 PM
ERROR:    Exception in ASGI application
12/22/2023
10:03:49 PM
Traceback (most recent call last):
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/anyio/streams/memory.py", line 98, in receive
12/22/2023
10:03:49 PM
    return self.receive_nowait()
12/22/2023
10:03:49 PM
           ^^^^^^^^^^^^^^^^^^^^^
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/anyio/streams/memory.py", line 93, in receive_nowait
12/22/2023
10:03:49 PM
    raise WouldBlock
12/22/2023
10:03:49 PM
anyio.WouldBlock
12/22/2023
10:03:49 PM
12/22/2023
10:03:49 PM
During handling of the above exception, another exception occurred:
12/22/2023
10:03:49 PM
12/22/2023
10:03:49 PM
Traceback (most recent call last):
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 78, in call_next
12/22/2023
10:03:49 PM
    message = await recv_stream.receive()
12/22/2023
10:03:49 PM
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/anyio/streams/memory.py", line 118, in receive
12/22/2023
10:03:49 PM
    raise EndOfStream
12/22/2023
10:03:49 PM
anyio.EndOfStream
12/22/2023
10:03:49 PM
12/22/2023
10:03:49 PM
During handling of the above exception, another exception occurred:
12/22/2023
10:03:49 PM
12/22/2023
10:03:49 PM
Traceback (most recent call last):
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
12/22/2023
10:03:49 PM
    result = await app(  # type: ignore[func-returns-value]
12/22/2023
10:03:49 PM
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
12/22/2023
10:03:49 PM
    return await self.app(scope, receive, send)
12/22/2023
10:03:49 PM
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1106, in __call__
12/22/2023
10:03:49 PM
    await super().__call__(scope, receive, send)
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
12/22/2023
10:03:49 PM
    await self.middleware_stack(scope, receive, send)
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
12/22/2023
10:03:49 PM
    raise exc
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
12/22/2023
10:03:49 PM
    await self.app(scope, receive, _send)
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/sessions.py", line 86, in __call__
12/22/2023
10:03:49 PM
    await self.app(scope, receive, send_wrapper)
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 108, in __call__
12/22/2023
10:03:49 PM
    response = await self.dispatch_func(request, call_next)
12/22/2023
10:03:49 PM
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/nicegui/storage.py", line 77, in dispatch
12/22/2023
10:03:49 PM
    response = await call_next(request)
12/22/2023
10:03:49 PM
               ^^^^^^^^^^^^^^^^^^^^^^^^
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
12/22/2023
10:03:49 PM
    raise app_exc
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
12/22/2023
10:03:49 PM
    await self.app(scope, receive_or_disconnect, send_no_error)
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 108, in __call__
12/22/2023
10:03:49 PM
    response = await self.dispatch_func(request, call_next)
12/22/2023
10:03:49 PM
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
12/22/2023
10:03:49 PM
  File "/plexwebdl-app/__main__.py", line 33, in check_auth
12/22/2023
10:03:49 PM
    return await call_next(request)
12/22/2023
10:03:49 PM
           ^^^^^^^^^^^^^^^^^^^^^^^^
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
12/22/2023
10:03:49 PM
    raise app_exc
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
12/22/2023
10:03:49 PM
    await self.app(scope, receive_or_disconnect, send_no_error)
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 108, in __call__
12/22/2023
10:03:49 PM
    response = await self.dispatch_func(request, call_next)
12/22/2023
10:03:49 PM
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/nicegui/middlewares.py", line 10, in dispatch
12/22/2023
10:03:49 PM
    response = await call_next(request)
12/22/2023
10:03:49 PM
               ^^^^^^^^^^^^^^^^^^^^^^^^
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
12/22/2023
10:03:49 PM
    raise app_exc
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
12/22/2023
10:03:49 PM
    await self.app(scope, receive_or_disconnect, send_no_error)
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
12/22/2023
10:03:49 PM
    raise exc
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
12/22/2023
10:03:49 PM
    await self.app(scope, receive, sender)
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
12/22/2023
10:03:49 PM
    raise e
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
12/22/2023
10:03:49 PM
    await self.app(scope, receive, send)
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
12/22/2023
10:03:49 PM
    await route.handle(scope, receive, send)
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
12/22/2023
10:03:49 PM
    await self.app(scope, receive, send)
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
12/22/2023
10:03:49 PM
    response = await func(request)
12/22/2023
10:03:49 PM
               ^^^^^^^^^^^^^^^^^^^
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 274, in app
12/22/2023
10:03:49 PM
    raw_response = await run_endpoint_function(
12/22/2023
10:03:49 PM
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
12/22/2023
10:03:49 PM
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
12/22/2023
10:03:49 PM
    return await dependant.call(**values)
12/22/2023
10:03:49 PM
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
12/22/2023
10:03:49 PM
  File "/plexwebdl-app/__main__.py", line 80, in download
12/22/2023
10:03:49 PM
    return FileResponse(part.file, filename=filename, stat_result=os.stat(part.file))
12/22/2023
10:03:49 PM
                                                                  ^^^^^^^^^^^^^^^^^^
12/22/2023
10:03:49 PM
FileNotFoundError: [Errno 2] No such file or directory: '/movies/Its a Wonderful Life (1946)/Its a Wonderful Life (1946).mkv'

```

**Comment by zdimension** [comment]
Seems like it can't access the file. Currently plexdlweb assumes it has access to the movies files through the same path as Plex, do you have the possibility of mounting your /movies folder in the plexdlweb container?

**Comment by siddpen** [comment]
I was wondering where the folders were being set, so that makes sense. I was able to mount the host folder to the container in the docker run command and could download successfully! Thanks again!
```
docker run --name plexwebdl-app -p 8766:8766 -v /mnt/user/data/media/tv/:/tv -v /mnt/user/data/media/movies/:/movies plexwebdl-app 
```
